# Generated by Django 5.1.3 on 2024-12-04 18:25
import os

import django.db.models.deletion
from django.db import migrations, models

from catalog_app.csv_import import import_csv
from cursova.settings import BASE_DIR


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_csv)
    ]
